# Bug report template helps capture reproducible issues.
name: "Bug report"
description: "Report a problem with the template"
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide a minimal reproduction.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, dependency versions.
