# Feature request template gathers desired enhancements.
name: "Feature request"
description: "Suggest an improvement to the template"
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this useful?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Other approaches you've considered.
