#!/usr/bin/env python3
"""Classify dependency licenses for AGPL compatibility review.

Copyright (C) 2026 Wiktor Hawrylik

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

DEFAULT_INPUT: str = "build/license-compliance/dependency-licenses.csv"
DEFAULT_OUTPUT: str = "build/license-compliance/dependency-license-audit.csv"

ALLOW_PATTERNS: tuple[str, ...] = (
    "MIT",
    "BSD",
    "Apache",
    "ISC",
    "PSF",
    "Python Software Foundation License",
    "Unlicense",
    "CC0",
    "Zlib",
    "LGPL",
    "GPL-3.0",
    "AGPL-3.0",
)
REVIEW_PATTERNS: tuple[str, ...] = (
    "MPL",
    "Unknown",
    "Dual",
    "Custom",
    "EULA",
)
BLOCK_PATTERNS: tuple[str, ...] = (
    "Proprietary",
    "CC BY-NC",
    "Non-Commercial",
    "GPL-2.0-only",
)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        Parsed command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Categorize dependency licenses into ALLOW/REVIEW/BLOCK.",
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=Path(DEFAULT_INPUT),
        help="Input CSV file generated by pip-licenses.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=Path(DEFAULT_OUTPUT),
        help="Output CSV file with compatibility category.",
    )
    return parser.parse_args()


def classify_license(license_text: str) -> str:
    """Classify a license string into ALLOW, REVIEW, or BLOCK.

    Args:
        license_text: Raw license value from `pip-licenses`.

    Returns:
        One of: "ALLOW", "REVIEW", or "BLOCK".
    """
    text = license_text.strip()
    if not text:
        return "REVIEW"

    lowered = text.lower()
    if any(pattern.lower() in lowered for pattern in BLOCK_PATTERNS):
        return "BLOCK"
    if any(pattern.lower() in lowered for pattern in REVIEW_PATTERNS):
        return "REVIEW"
    if any(pattern.lower() in lowered for pattern in ALLOW_PATTERNS):
        return "ALLOW"
    return "REVIEW"


def build_audit_rows(input_csv: Path) -> list[dict[str, str]]:
    """Build categorized audit rows from raw dependency license CSV.

    Args:
        input_csv: CSV produced by `pip-licenses`.

    Returns:
        Rows enriched with computed `Category`.
    """
    rows: list[dict[str, str]] = []
    with input_csv.open(encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            license_value = row.get("License", "")
            rows.append(
                {
                    "Name": row.get("Name", ""),
                    "Version": row.get("Version", ""),
                    "License": license_value,
                    "Category": classify_license(license_value),
                    "Author": row.get("Author", ""),
                    "URL": row.get("URL", ""),
                }
            )
    return rows


def write_audit_csv(output_csv: Path, rows: list[dict[str, str]]) -> None:
    """Write dependency license audit results to CSV.

    Args:
        output_csv: Destination path.
        rows: Categorized dependency rows.
    """
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["Name", "Version", "License", "Category", "Author", "URL"]
    with output_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    """Run dependency license classification and enforce block failures."""
    args = parse_args()
    rows = build_audit_rows(args.input_csv)
    write_audit_csv(args.output_csv, rows)

    blocked = [row for row in rows if row["Category"] == "BLOCK"]
    review = [row for row in rows if row["Category"] == "REVIEW"]

    print(f"Dependencies audited: {len(rows)}")
    print(f"Blocked licenses: {len(blocked)}")
    print(f"Review-required licenses: {len(review)}")

    if blocked:
        print("Blocked dependencies:")
        for row in blocked:
            print(f"- {row['Name']} {row['Version']}: {row['License']}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
